project:
  type: website
  output-dir: docs

website:
  title: "Edmond Kwan MBBS PhD FRACP"
  
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: presentations.qmd
        text: Presentations

format:
  html:
    theme: flatly #flatly/darkly also nice
    css: styles.css
    toc: false

